// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlu_x_9ObyaVSlVhTfTVsS_cW5q1djIg',
    appId: '1:65151645526:web:686e17487fd2d55bd748f7',
    messagingSenderId: '65151645526',
    projectId: 'estude-ai-puc',
    authDomain: 'estude-ai-puc.firebaseapp.com',
    storageBucket: 'estude-ai-puc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLOEHV4wS-f0UWconxkpsPl2MUTVPYYlY',
    appId: '1:65151645526:android:c58b6be4555c305dd748f7',
    messagingSenderId: '65151645526',
    projectId: 'estude-ai-puc',
    storageBucket: 'estude-ai-puc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZqTOgmCx2x_yUoV00nuVQO9Su3DcV2Co',
    appId: '1:65151645526:ios:f7eb5b8b946633ecd748f7',
    messagingSenderId: '65151645526',
    projectId: 'estude-ai-puc',
    storageBucket: 'estude-ai-puc.firebasestorage.app',
    iosBundleId: 'com.estudai.estudeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZqTOgmCx2x_yUoV00nuVQO9Su3DcV2Co',
    appId: '1:65151645526:ios:f7eb5b8b946633ecd748f7',
    messagingSenderId: '65151645526',
    projectId: 'estude-ai-puc',
    storageBucket: 'estude-ai-puc.firebasestorage.app',
    iosBundleId: 'com.estudai.estudeai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFlu_x_9ObyaVSlVhTfTVsS_cW5q1djIg',
    appId: '1:65151645526:web:f4956ae64a8fa601d748f7',
    messagingSenderId: '65151645526',
    projectId: 'estude-ai-puc',
    authDomain: 'estude-ai-puc.firebaseapp.com',
    storageBucket: 'estude-ai-puc.firebasestorage.app',
  );
}
