name: estudeai
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0+3
  image_picker: ^1.1.1
  permission_handler: 11.3.1
  flutter_plugin_android_lifecycle: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/verified.png
    - assets/images/default.png
